// This is the main file for the Netlify Build plugin inngest.
// Please read the comments to learn more about the Netlify Build plugin syntax.
// Find more information in the Netlify documentation.

/* eslint-disable no-unused-vars */

// Runs on build success
export const onSuccess = async function ({
  // Whole configuration file. For example, content of `netlify.toml`
  netlifyConfig,
  // Users can pass configuration inputs to any plugin in their Netlify
  // configuration file.
  // For example:
  //
  //   [[plugins]]
  //   package = "netlify-plugin-inngest"
  //     [plugins.inputs]
  //     foo = "bar"
  inputs,
  // `onError` event handlers receive the error instance as argument
  error,

  // Build constants
  constants: {
    // Path to the Netlify configuration file. `undefined` if none was used
    CONFIG_PATH,
    // Directory that contains the deploy-ready HTML files and assets
    // generated by the build. Its value is always defined, but the target
    // might not have been created yet.
    PUBLISH_DIR,
    // The directory where function source code lives.
    // `undefined` if not specified by the user.
    FUNCTIONS_SRC,
    // The directory where built serverless functions are placed before
    // deployment. Its value is always defined, but the target might not have
    // been created yet.
    FUNCTIONS_DIST,
    // Boolean indicating whether the build was run locally (Netlify CLI) or
    // in the production CI
    IS_LOCAL,
    // Version of Netlify Build as a `major.minor.patch` string
    NETLIFY_BUILD_VERSION,
    // The Netlify Site ID
    SITE_ID,
  },

  // Core utilities
  utils: {
    // Utility to report errors.
    // See https://github.com/netlify/build#error-reporting
    build,
    // Utility to display information in the deploy summary.
    // See https://github.com/netlify/build#logging
    status,
    // Utility for caching files.
    // See https://github.com/netlify/build/blob/master/packages/cache-utils#readme
    cache,
    // Utility for running commands.
    // See https://github.com/netlify/build/blob/master/packages/run-utils#readme
    run,
    // Utility for dealing with modified, created, deleted files since a git commit.
    // See https://github.com/netlify/build/blob/master/packages/git-utils#readme
    git,
    // Utility for handling Netlify Functions.
    // See https://github.com/netlify/build/tree/master/packages/functions-utils#readme
    functions,
  },
}) {
  let url

  try {
    url = new URL("/api/inngest", process.env.URL)
  } catch (err) {
    return void build.failPlugin(
      'Invalid or no URL found as Inngest plugin input; please specify a URL to access your functions once deployed',
    )
  }

  try {
    await run('curl', ['-X', 'PUT', url, '-v'])
  } catch (error) {
    return void build.failPlugin(
      `Failed to ping deployed Inngest functions. Check that the input URL "${url}" is correct.`,
    )
  }

  status.show({ summary: 'Success!' })
}
